# Config format for actions/labeler@v5
# https://github.com/actions/labeler#configuration

docs:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
          - '**/*.md'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

tests:
  - changed-files:
      - any-glob-to-any-file:
          - src/**/*.test.ts
          - src/**/*.spec.ts

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - pnpm-lock.yaml

source:
  - changed-files:
      - any-glob-to-any-file:
          - src/**
