const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['intro', 'installation', 'getting-started', 'examples'],
    },
    {
      type: 'category',
      label: 'User Guide',
      items: [
        'user-guide/index',
        'user-guide/how-it-works',
        'user-guide/configuration',
        'user-guide/features',
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      items: [
        'developer-guide/index',
        'developer-guide/data-model',
        'developer-guide/testing',
        'developer-guide/contributing',
        'developer-guide/architecture',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/index',
        'architecture/constitution',
        'architecture/data-model',
        'architecture/project',
        'architecture/api-layer',
        'architecture/ui',
        'architecture/quality-checks',
        'architecture/testing-plan',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['reference/cli', 'reference/configuration', 'reference/hooks'],
    },
    {
      type: 'autogenerated',
      dirName: 'api',
    },
    {
      type: 'category',
      label: 'Research',
      items: ['research/real-world-demand', 'research/competitor-analysis'],
    },
    {
      type: 'category',
      label: 'Post-mortems',
      link: {
        type: 'generated-index',
        title: 'Post-mortems',
        description: 'Retrospectives and incident analyses.',
      },
      items: [{ type: 'autogenerated', dirName: 'post-mortems' }],
    },
    'changelog',
  ],
};

export default sidebars;
